services:
  resourcespace:
    build: .
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - STAGE=${STAGE}
      - MYSQL_SERVER=${MYSQL_SERVER}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_READ_ONLY_USER=${MYSQL_READ_ONLY_USER}
      - MYSQL_READ_ONLY_PASSWORD=${MYSQL_READ_ONLY_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - DB_NAME=${DB_NAME}
      - SCRAMBLE_KEY=${SCRAMBLE_KEY}
      - API_SCRAMBLE_KEY=${API_SCRAMBLE_KEY}
      - EMAIL_NOTIFY=${EMAIL_NOTIFY}
      - EMAIL_FROM=${EMAIL_FROM}
    depends_on:
      - mariadb
    volumes:
      - rs_config:/var/www/html/include
      - rs_assets:/var/www/html/filestore
    networks:
      - frontend
      - backend
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resourcespace.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.resourcespace.entrypoints=websecure"
      - "traefik.http.routers.resourcespace.tls.certresolver=letsencrypt"
      - "traefik.http.services.resourcespace.loadbalancer.server.port=80"

  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      - DB_HOST=mariadb
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_READ_ONLY_USER}
      - MARIADB_PASSWORD=${MYSQL_READ_ONLY_PASSWORD}
      - SCRAMBLE_KEY=${SCRAMBLE_KEY}
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
  dokploy-network:
    external: true

volumes:
  mariadb:
  rs_config:
  rs_assets:
