services:
  resourcespace:
    build: .
    restart: unless-stopped
    environment:
      - MYSQL_SERVER=${MYSQL_SERVER}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_READ_ONLY_USER}
      - MYSQL_PASSWORD=${MYSQL_READ_ONLY_PASSWORD}
    depends_on:
      - mariadb
    volumes:
      - rs_config:/var/www/html/include
      - rs_assets:/var/www/html/filestore
    networks:
      - frontend
      - backend
      - dokploy-network

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      - DB_HOST=mariadb
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_READ_ONLY_USER}
      - MARIADB_PASSWORD=${MYSQL_READ_ONLY_PASSWORD}
      - SCRAMBLE_KEY=${SCRAMBLE_KEY}
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
  dokploy-network:
    external: true

volumes:
  mariadb:
  rs_config:
  rs_assets:
